// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RestaurantApi.Data;

#nullable disable

namespace RestaurantApi.Migrations
{
    [DbContext(typeof(RestaurantDbContext))]
    [Migration("20260527085838_UpdateTableSeedTokens")]
    partial class UpdateTableSeedTokens
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("RestaurantApi.Models.CancelledOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CancelledAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Price")
                        .HasColumnType("REAL");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TableId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TableName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("CancelledOrders");
                });

            modelBuilder.Entity("RestaurantApi.Models.Invoice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("OrderDetails")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TableId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TableName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("TotalAmount")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Invoices");
                });

            modelBuilder.Entity("RestaurantApi.Models.MenuItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsHot")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("MenuItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Hải Sản",
                            ImageUrl = "https://images.unsplash.com/photo-1559742811-822873691df8?w=600&q=80",
                            IsHot = false,
                            Name = "Mực Hấp Gừng",
                            Price = 150000m
                        },
                        new
                        {
                            Id = 2,
                            Category = "Hải Sản",
                            ImageUrl = "https://images.unsplash.com/photo-1615141982883-c7ad0e69fd62?w=600&q=80",
                            IsHot = true,
                            Name = "Tôm Hùm Nướng Phô Mai",
                            Price = 550000m
                        },
                        new
                        {
                            Id = 3,
                            Category = "Lẩu",
                            ImageUrl = "https://images.unsplash.com/photo-1569050467447-ce54b3bbc37d?w=600&q=80",
                            IsHot = true,
                            Name = "Lẩu Thái Tomyum",
                            Price = 250000m
                        },
                        new
                        {
                            Id = 4,
                            Category = "Lẩu",
                            ImageUrl = "https://images.unsplash.com/photo-1547592166-23ac45744acd?w=600&q=80",
                            IsHot = false,
                            Name = "Lẩu Nấm Chim Câu",
                            Price = 300000m
                        },
                        new
                        {
                            Id = 5,
                            Category = "Đồ Nướng",
                            ImageUrl = "https://images.unsplash.com/photo-1558030006-450675393462?w=600&q=80",
                            IsHot = true,
                            Name = "Bò Tảng Nướng",
                            Price = 200000m
                        },
                        new
                        {
                            Id = 6,
                            Category = "Đồ Nướng",
                            ImageUrl = "https://images.unsplash.com/photo-1544025162-d76694265947?w=600&q=80",
                            IsHot = true,
                            Name = "Sườn Nướng BBQ",
                            Price = 180000m
                        },
                        new
                        {
                            Id = 7,
                            Category = "Đồ Uống",
                            ImageUrl = "https://images.unsplash.com/photo-1608270586620-248524c67de9?w=600&q=80",
                            IsHot = false,
                            Name = "Bia Heineken",
                            Price = 25000m
                        },
                        new
                        {
                            Id = 8,
                            Category = "Đồ Uống",
                            ImageUrl = "https://images.unsplash.com/photo-1622597467836-f3e6707fd04f?w=600&q=80",
                            IsHot = false,
                            Name = "Nước Ép Dưa Hấu",
                            Price = 35000m
                        });
                });

            modelBuilder.Entity("RestaurantApi.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OrderDetails")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TableId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TableName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("TotalAmount")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("RestaurantApi.Models.Table", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CurrentSessionToken")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsOccupied")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("ServiceCharge")
                        .HasColumnType("REAL");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Tables");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CurrentSessionToken = "d8a3c9b2",
                            IsOccupied = false,
                            Name = "Bàn 1",
                            ServiceCharge = 0.0,
                            Type = "Standard"
                        },
                        new
                        {
                            Id = 2,
                            CurrentSessionToken = "e7b1f5a4",
                            IsOccupied = false,
                            Name = "Bàn 2",
                            ServiceCharge = 0.0,
                            Type = "Standard"
                        },
                        new
                        {
                            Id = 3,
                            CurrentSessionToken = "9c2d8e3f",
                            IsOccupied = false,
                            Name = "Bàn 3",
                            ServiceCharge = 0.0,
                            Type = "Standard"
                        },
                        new
                        {
                            Id = 4,
                            CurrentSessionToken = "f4a5c9d1",
                            IsOccupied = false,
                            Name = "Phòng VIP 1",
                            ServiceCharge = 100000.0,
                            Type = "VIP"
                        },
                        new
                        {
                            Id = 5,
                            CurrentSessionToken = "b8e2f6a7",
                            IsOccupied = false,
                            Name = "Phòng VIP 2",
                            ServiceCharge = 150000.0,
                            Type = "VIP"
                        });
                });

            modelBuilder.Entity("RestaurantApi.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PasswordHash = "eb833233713a8d47d7e1d9aaed85c6ce48fb0981e3892615d547970997a656bf",
                            Role = "Admin",
                            Username = "admin"
                        },
                        new
                        {
                            Id = 2,
                            PasswordHash = "be36aea9f5ac8fbbe362b3c6fe9bf3717afce9d20a7a08e35031278161084883",
                            Role = "Cashier",
                            Username = "cashier"
                        },
                        new
                        {
                            Id = 3,
                            PasswordHash = "8504a0f2c41be46d60bb1f151bcf6b510fd6d96ca2a257fbf947f3b644356215",
                            Role = "Kitchen",
                            Username = "kitchen"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
