// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RestaurantApi.Data;

#nullable disable

namespace RestaurantApi.Migrations
{
    [DbContext(typeof(RestaurantDbContext))]
    [Migration("20260526083912_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("RestaurantApi.Models.MenuItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsHot")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("MenuItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Hải Sản",
                            ImageUrl = "https://images.unsplash.com/photo-1559742811-822873691df8?w=600&q=80",
                            IsHot = false,
                            Name = "Mực Hấp Gừng",
                            Price = 150000m
                        },
                        new
                        {
                            Id = 2,
                            Category = "Hải Sản",
                            ImageUrl = "https://images.unsplash.com/photo-1615141982883-c7ad0e69fd62?w=600&q=80",
                            IsHot = true,
                            Name = "Tôm Hùm Nướng Phô Mai",
                            Price = 550000m
                        },
                        new
                        {
                            Id = 3,
                            Category = "Lẩu",
                            ImageUrl = "https://images.unsplash.com/photo-1569050467447-ce54b3bbc37d?w=600&q=80",
                            IsHot = true,
                            Name = "Lẩu Thái Tomyum",
                            Price = 250000m
                        },
                        new
                        {
                            Id = 4,
                            Category = "Lẩu",
                            ImageUrl = "https://images.unsplash.com/photo-1547592166-23ac45744acd?w=600&q=80",
                            IsHot = false,
                            Name = "Lẩu Nấm Chim Câu",
                            Price = 300000m
                        },
                        new
                        {
                            Id = 5,
                            Category = "Đồ Nướng",
                            ImageUrl = "https://images.unsplash.com/photo-1558030006-450675393462?w=600&q=80",
                            IsHot = true,
                            Name = "Bò Tảng Nướng",
                            Price = 200000m
                        },
                        new
                        {
                            Id = 6,
                            Category = "Đồ Nướng",
                            ImageUrl = "https://images.unsplash.com/photo-1544025162-d76694265947?w=600&q=80",
                            IsHot = true,
                            Name = "Sườn Nướng BBQ",
                            Price = 180000m
                        },
                        new
                        {
                            Id = 7,
                            Category = "Đồ Uống",
                            ImageUrl = "https://images.unsplash.com/photo-1608270586620-248524c67de9?w=600&q=80",
                            IsHot = false,
                            Name = "Bia Heineken",
                            Price = 25000m
                        },
                        new
                        {
                            Id = 8,
                            Category = "Đồ Uống",
                            ImageUrl = "https://images.unsplash.com/photo-1622597467836-f3e6707fd04f?w=600&q=80",
                            IsHot = false,
                            Name = "Nước Ép Dưa Hấu",
                            Price = 35000m
                        });
                });

            modelBuilder.Entity("RestaurantApi.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("TableId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("RestaurantApi.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsCooked")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MenuItemId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OrderId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MenuItemId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("RestaurantApi.Models.Table", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsOccupied")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Tables");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsOccupied = false,
                            Name = "Bàn 1"
                        },
                        new
                        {
                            Id = 2,
                            IsOccupied = false,
                            Name = "Bàn 2"
                        },
                        new
                        {
                            Id = 3,
                            IsOccupied = false,
                            Name = "Bàn 3"
                        },
                        new
                        {
                            Id = 4,
                            IsOccupied = false,
                            Name = "Bàn 4"
                        });
                });

            modelBuilder.Entity("RestaurantApi.Models.OrderItem", b =>
                {
                    b.HasOne("RestaurantApi.Models.MenuItem", "MenuItem")
                        .WithMany()
                        .HasForeignKey("MenuItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RestaurantApi.Models.Order", null)
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MenuItem");
                });

            modelBuilder.Entity("RestaurantApi.Models.Order", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
